---
title: "Программа курса"
output: pdf_document
lang: russian
fontsize: 10 pt
---

1. Первичная обработка данных
  - общие принципы организации данных
  - загрузка данных в R
  - описательные статистики
  - преобразования переменных
  - группировка, сортировка, групповые описательные статистики
  - отбор наблюдений
  - выборочное изменение наблюдений
  - слияние нескольких таблиц

2. Графики
  - стандартные графики (диаграмма рассеяния, гистограмма)
  - матрица диаграмм рассеяния
  - мозаичный график
  - виолончельные график
  - подход грамматики графиков 
  
3. Регрессия для перекрестной выборки
  - регрессия с факторными объясняющими переменными
  - визуализация результатов построения регрессии
  - робастные стандартные ошибки
  
4. Модели для качественной зависимой переменной
  - логит и пробит
  - прогнозирование в логит и пробит моделях
  - алгоритм случайного леса *
  
5. Модели временных рядов
  - стационарные ряды
  - переход к приращениям для получения стационарного ряда
  - модели класса ARMA
  - автокорреляционная и частная автокорреляционная функции
  - штрафные критерии AIC, BIC
  - автоматический выбор модели класса ARMA
  - прогнозирование
  - тета-метод *
  - экспоненциальное сглаживание *
  
6. Модели панельных данных
  - сквозные модели
  - модели с фиксированными эффектами
  - модели со случайными эффектами
  - выбор модели
  
  
  